### ISSUE TITLE
Description of changes in the game session

### ISSUE THREAD

**Issue by vjcortesa** [averbraeck/housinggame-admin#42]
- [ ] A new Game version 2024-4 English, was created with a game Session Test game play with and without. Is it possible to play sessions with previous game versions?
- [ ] On a new version, there is no space for writing what the session is about or what the main changes with previous sessions are, for example, 2024-4 is a clone of the Game Version 2023-09 English, for example, changes are about: Sand bags only applicable to river because in Jarno's game they were set as such. Also makes the point that for rain sufficient warning time is needed to place them ahead. Automatic steel walls give protection to river and rain and do not provide satisfaction, all rest was the same. News and # of rounds are 4.

![Housing game administration](https://github.com/averbraeck/housinggame-admin/assets/8215750/234ccf87-ab61-4143-ada7-cb39fb678905)

**Comment by averbraeck** [comment]
Task 1: Sessions can be created for any version of the game. Old versions and new versions of the game co-exist.

**Comment by averbraeck** [comment]
Task 2: See https://github.com/averbraeck/housinggame-common/issues/25.
